### PR TITLE
feat: questions page

### PR DESCRIPTION
**Pull request by bharati-21**
- This page contains the following components:
   - question text
   - options buttons
   - Buttons to navigate to the previous and next pages

### CODE REVIEW

**Review by sonishreyas — APPROVED** [review]
Code looks good and easy to understand.

**Review by ravikumar0403 — APPROVED** [review]
code is clean and readable.

**Comment by bharati-21** [comment]
> Code looks good and easy to understand.

Thank you for your review!

**Comment by bharati-21** [comment]
> code is clean and readable.

Thank you for your review!

**Pull request merged**
