### PR TITLE
Feat: results page

### PR DESCRIPTION
**Pull request by bharati-21**
This page has the following components:
- Total points user has scored
- List of questions, users choices indicating the incorrect and (or) correct choices.

image

### CODE REVIEW

**Review by SHIKHASINGH1506 — APPROVED** [review]
No changes required.  I can see your utility classes are helping you out in css. That's great!

**Review by ivinayakg — APPROVED** [review]
You have used the utility classes brilliantly, I'm taking notes.

**Comment by bharati-21** [comment]
> No changes required. I can see your utility classes are helping you out in css. That's great!

Thank you for your review!

**Comment by bharati-21** [comment]
> You have used the utility classes brilliantly, I'm taking notes.

Thank you for your review!

**Pull request merged**
