### PR TITLE
Feat: Rules page basic structure

### PR DESCRIPTION
**Pull request by bharati-21**
- Created the basic structure and styles of the rules page
   - Contains rules for the quiz
   - CTA button to navigate users to the questions for the selected category.

### CODE REVIEW

**Review by rohit8686 — APPROVED** [review]
Everything looks good !

**Review by stutisk — COMMENTED** [review]
code looks clean to me , can go forward with merging it !

**Comment by bharati-21** [comment]
> Everything looks good !

Thank you for your review!

**Comment by bharati-21** [comment]
> code looks clean to me , can go forward with merging it !

Thank you for your review!

**Pull request merged**
